version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  api:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./api
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myDbUser
      - MONGO_INITDB_ROOT_PASSWORD=myPassDB
      - MONGO_PORT=27017
    links:
      - mongo
